<template>
  <div class="boxBg privacy">
    <div class="cen">
      <div class="nav_header listBg titleColor">
        {{ $t('Footer.arr.twelve') }}
      </div>
      <div class="agree_box listBg navColor">
        <pre class="font-Four" v-show="$i18n.locale == 'CN'">
 本隱私權聲明適用本平臺的所有相關服務，本平臺尊重並保護所有使用本平臺平臺服務用戶的個人隱私權。 為了給您提供更準確、更有個性化的服務，會按照本隱私權政策的規定使用和披露您的個人資訊但本平臺將以高度的勤勉、審慎義務對待這些資訊。 除本隱私權政策另有規定外，在未征得您事先許可的情况下，本平臺不會將這些資訊對外披露或向協力廠商提供。 本平臺會不時更新本隱私權政策。 您在同意本平臺服務協定之時，即視為您已經同意本隱私權政策全部內容。 本隱私權政策屬於服務協定不可分割的一部分。
1.使用範圍
在您注册或啟動可以登入我們平臺的帳戶時，您在我們其關聯公司提供的其他平臺提供的個人註冊資訊（應法律法規要求需公示的企業名稱等相關工商注册資訊以及自然人經營者的資訊除外）； 在您使用本平臺，或本平臺網頁時，本平臺並記錄的您的瀏覽器和電腦上的資訊，包括但不限於您的IP地址、瀏覽器的類型、使用的語言、訪問日期和時間、軟硬體特徵資訊及您需求的網頁記錄等數據； 本平臺途徑從商業夥伴處取得的用戶個人數據。
2.資訊使用
我們不會向任何無關協力廠商提供、出售、出租、分享或交易您的個人資訊，除非事先得到您的許可，或該協力廠商和我們（含我們關聯公司）單獨或共同為您提供服務，且在該服務結束後，其將被禁止訪問包括其以前能够訪問的所有這些資料。 我們亦不允許任何協力廠商以任何手段收集、編輯、出售或者無償傳播您的個人資訊。 任何我們平臺用戶如從事上述活動，一經發現，我們有權立即終止與該用戶的服務協定。
3.資訊披露
在如下情况下，我們將依據您的個人意願或法律的規定全部或部分的披露您的個人資訊：經您事先同意，向協力廠商披露； 如您是適格的知識產權投訴人並已提起投訴，應被投訴人要求，向被投訴人披露，以便雙方處理可能的權利糾紛； 根據法律的有關規定，或者行政或司法機构的要求，向協力廠商或者行政、司法機构披露； 如您出現違反有關法律、法規或者我們服務協定或相關規則的情况，需要向協力廠商披露； 為提供您所要求的產品和服務，而必須和協力廠商分享您的個人資訊； 在我們平臺上創建的某一交易中，如交易任何一方履行或部分履行了交易義務並提出資訊披露請求的，我們有權决定向該用戶提供其交易對方的聯絡方式等必要資訊，以促成交易的完成或糾紛的解决。 我們根據法律、法規或者網站政策認為合適的披露。
4.資訊存儲和交換
我們收集的有關您的資訊和資料將保存在我們及（或）其關聯公司的服務器上，這些資訊和資料可能傳送至您所在國家、地區或我們收集資訊和資料所在地的境外並在境外被訪問、存儲和展示。
5.Cookie的使用
在您未拒絕接受cookies的情况下，我們會在您的電腦上設定或取用cookies，以便您能登入或使用依賴於cookies的我們平臺服務或功能。 我們使用cookies可為您提供更加周到的個性化服務包括推廣服務。 您有權選擇接受或拒絕接受cookies。 您可以通過修改瀏覽器設定的筦道拒絕接受cookies。 但如果您選擇拒絕接受cookies，則您可能無法登入或使用依賴於cookies的我們平臺服務或功能。
6.資訊安全
您的帳戶均有安全保護功能，請妥善保管您的帳戶及密碼資訊。 我們將通過向其它服務器備份、對使用者密碼進行加密等安全措施確保您的資訊不遺失，不被濫用和變造。 儘管有前述安全措施，但同時也請您注意在資訊網路上不存在“完善的安全措施”。 在使用我們平臺服務進行網上交易時，您不可避免的要向交易對方或潜在的交易對方披露自己的個人資訊，如聯絡方式或者郵政地址。 請您妥善保護自己的個人資訊，僅在必要的情形下向他人提供。 如您發現自己的個人資訊洩密，尤其是你的帳戶及密碼發生洩露，請您立即聯絡我們客服，以便我們採取相應措施。
未成年人的特別注意事項如果您不是具備完全民事權利能力和完全民事行為能力的自然人，您無權使用我們平臺服務，囙此我們希望您不要向我們提供任何個人資訊。
您的帳戶服務被終止或者帳戶在本平臺的許可權被永久凍結（註銷）後，本平臺沒有義務為您保留或向您披露您帳戶中的任何資訊，也沒有義務向您或協力廠商轉發任何您未曾閱讀或發送過的資訊。 您同意，您與本平臺的契約關係終止後，本平臺仍享有下列權利：繼續保存您的用戶資訊及您使用本平臺服務期間的所有交易資訊。 您在使用本平臺服務期間存在違法行為或違反本協定和/或規則的行為的，本平臺仍可依據本協定向您主張權利。 本平臺中止或終止向您提供本平臺服務後，對於您在服務中止或終止之前的交易行為依下列原則處理，您應獨力處理並完全承擔進行以下處理所產生的任何爭議、損失或新增的任何費用， 並應確保本平臺免於囙此產生任何損失或承擔任何費用：您在服務中止或終止之前已經上傳至本平臺的比特幣等虛擬貨幣等虛擬貨幣尚未交易的，本平臺有權在中止或終止服務的同時删除此項物品的相關資訊； 您在服務中止或終止之前已經與其他會員達成買賣契約，但契約尚未實際履行的，本平臺有權删除該買賣契約及其交易比特幣等虛擬貨幣等虛擬貨幣的相關資訊； 您在服務中止或終止之前已經與其他會員達成買賣契約且已部分履行的，本平臺可以不删除該項交易，但本平臺有權在中止或終止服務的同時將相關情形通知您的交易對方。
7.隱私權政策
本平臺將在本平臺站公佈並不定時修訂隱私權政策，隱私權政策構成本協定的有效組成部分。
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'EN'">
       This privacy statement applies to all related services of this platform, and this platform respects and protects the personal privacy of all users who use this platform's services. In order to provide you with more accurate and personalized services, your personal information will be used and disclosed in accordance with the provisions of this Privacy Policy, but this platform will treat such information with a high degree of diligence and prudence. Except as otherwise provided in this Privacy Policy, this platform will not disclose or provide this information to third parties without your prior permission. This platform will update this privacy policy from time to time. When you agree to the service agreement of this platform, you are deemed to agree to the entire content of this privacy policy. This Privacy Policy is an integral part of the Service Agreement.

1. Scope of use
When you register or activate an account that can log in to our platform, the personal registration information provided by our affiliated companies on other platforms (except for the company name and other relevant industrial and commercial registration information, which needs to be published as required) laws and regulations, natural person business user information)); when you use this platform or its web pages, this platform will also record information on your browser and computer, including but not limited to your IP address, browser type, language used, access Date and time, software and other data and hardware function information, as well as web page records you need; user personal data obtained by this platform from business partners.
2. Information use
We will not provide, sell, rent, share or trade your personal information to any unrelated third party unless we obtain your prior permission, or the third party and us (including our affiliates) individually or jointly provide services to you , and at the end of the service, it will be disabled from accessing all such materials, including previously able access materials. We also do not allow any third party to collect, edit, sell or disseminate your personal information in any way for free. If any user of our platform engages in the above activities, we have the right to terminate the service agreement with the user immediately upon discovery.
3. Information disclosure
We will disclose your personal information in whole or in part according to your personal wishes or legal requirements in the following cases: Disclosure to a third party with your prior consent; if you are a qualified intellectual property complainant and have made a complaint, you should be complained According to the relevant provisions of the law, or the requirements of administrative or judicial institutions, it is provided to third-party manufacturers or administrative or judicial institutions; laws, regulations or our The service agreement or related rules need to be disclosed to third parties; in order to provide the products and services you need, you must share your personal information with third parties; in transactions created on our platform, if any party to the transaction performs or partially performs In order to meet the transaction obligations and information disclosure requests, we have the right to decide to provide users with necessary information such as the contact information of the counterparty to facilitate the completion of the transaction or the resolution of disputes. Disclosures we deem appropriate in accordance with laws, regulations or site policies.
4. Information storage and exchange
The information and data we collect about you will be stored on our and/or our affiliates' servers and may be transferred to and accessed outside of your country, region or location where we collect the information and data , store and display.
5. Use of Cookies
If you do not refuse to accept cookies, we will set or access cookies on your computer in order for you to log in or use our platform services or features that rely on cookies. We use cookies to provide you with a more thoughtful and personalized service, including promotional services. You have the right to choose to accept or reject cookies. You can refuse to accept cookies by modifying the channels set by your browser. However, if you choose to refuse cookies, you may not be able to log in or use our platform services or features that rely on cookies.
6. Information Security
Your account has security protection function, please keep your account and password information properly. We will ensure that your information is not lost, abused, or tampered with through security measures such as backing up to other servers and encrypting user passwords. Notwithstanding the above security measures, please note that there are no "perfect security measures" o
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'JP'">
       このプライバシーステートメントは、このプラットフォームのすべての関連サービスに適用され、このプラットフォームのサービスのすべてのユーザーの個人のプライバシーを尊重および保護します。より正確でパーソナライズされたサービスを提供するために、お客様の個人情報はこのプライバシーポリシーの規定に従って使用および開示されますが、プラットフォームはこの情報を細心の注意を払って扱います。このプライバシーポリシーに別段の定めがある場合を除き、プラットフォームは事前の許可なしにこの情報を第三者に開示または提供することはありません。このプラットフォームは、このプライバシーポリシーを随時更新します。このプラットフォームのサービス契約に同意することにより、このプライバシーポリシーの内容全体に同意したことになります。このプライバシーポリシーは、当社のサービス契約の不可欠な部分です。

1.使用範囲
当社のプラットフォームへのログインを可能にするアカウントを登録またはアクティブ化する場合、当社の関連会社が提供する他のプラットフォームによって提供される個人登録情報（ただし、必要に応じて開示する必要のある商号およびその他の関連する事業名を提供）。 （産業および商業登録情報を除く）法規制、自然人オペレーター情報）））;このプラットフォームまたはそのWebページを使用する場合、このプラットフォームにはIPアドレスとブラウザーの種類が含まれますが、これらに限定されません。そうでないブラウザとコンピュータ。言語、アクセス日時、ソフトウェアおよびハードウェア機能情報、必要なWebページの記録、このプラットフォームによってビジネスパートナーから取得されたユーザーの個人データおよびその他のデータを使用します。
2.情報の使用
当社が個別に、または第三者（当社の関連会社を含む）と共同でサービスを提供する場合を除き、お客様の事前の許可なしにお客様の個人情報を第三者として使用することはありません。私たちはあなたと提供、販売、賃貸、共有、または取引することはありません。最後に、以前にアクセス可能な資料を含む、そのようなすべての資料へのアクセスは禁止されています。また、第三者がお客様の個人情報を無料で収集、編集、販売、または配布することを許可していません。上記の活動のいずれかに従事する当社のプラットフォームのユーザーである場合、当社は発見後直ちにお客様とのサービス契約を終了する権利を留保します。
3.情報開示
以下の場合、お客様の個人的な希望や法的要件に応じて、お客様の個人情報の全部または一部を開示します。お客様の事前の同意を得た第三者への開示。あなたが知的財産権の有資格の請求者であり、苦情を申し立てた場合、両当事者が起こりうる権利紛争に対処できるように、回答者の要求に応じて回答者に開示します。必要な製品を提供するために、製造業者または政府機関または司法機関、法律、規制、または当社のサービス契約または関連規則を、法律の関連規定または政府機関または司法機関の要件に従って第三者に開示する必要があります。およびサービスについては、個人情報を第三者と共有する必要があります。取引の作成において、当社のプラットフォームでの取引の当事者は、取引義務と情報開示を要求します。履行または部分履行の場合、取引または紛争を解決するために、取引先の連絡先などの必要な情報を提供します。法律、規制、またはサイトポリシーによって適切と見なされる開示。
4.情報の保管と交換
当社がお客様に関して収集する情報およびデータは、当社および/または当社の関連サーバーに保存され、当社が情報およびデータを収集するお客様の国、地域、または場所の外に送信およびアクセスされる場合があります。ストレージと表示。
5.クッキーの使用
お客様がCookieの受け入れを拒否しない場合、お客様がログインしてCookieに依存する当社のプラットフォームサービスまたは機能を使用できるように、お客様のコンピューターを設定またはアクセスします。弊社はCookieを使用して、プロモーションオファーなど、より思慮深くパーソナライズされたサービスを提供します。あなたには、Cookieを受け入れるか拒否するかを選択する権利があります。ブラウザのチャネル設定を変更することにより、Cookieの受け入れを拒否できます。ただし、Cookieを拒否することを選択した場合、Cookieに依存する当社のプラットフォームサービスまたは機能にログインまたは使用できない場合があります。
6.情報セキュリティ
アカウントにはセキュリティ機能があるため、アカウントとパスワードの情報を正しく保存してください。他のサーバーへのバックアップやユーザーパスワードの暗号化などのセキュリティ対策により、お客様の情報の紛失、誤用、改ざんを防止します。上記のセキュリティ対策にもかかわらず、情報ネットワークには「完璧なセキュリティ対策」がないことに注意してください。当社のプラットフォームサービスを使用してオンライン取引を行う場合、連絡先の詳細や住所などの個人情報を他の当事者または潜在的な当事者に開示することは避けられません。個人情報は適切に保護し、必要な場合にのみ他者に提供してください。個人情報、特にアカウント番号やパスワードが漏洩した場合は、すぐにカスタマーサービスにご連絡いただければ返信いたします。
未成年者への特別な通知あなたが市民であり、完全な公民権を持つ自然人でない限り、私たちのプラットフォームサービスを使用する権利がないため、個人情報を提供しないでください。

       アカウントが機能しなくなった後、またはプラットフォームでのアカウントの権限が完全に凍結（キャンセル）された後、プラットフォームはアカウント内の情報を保持または開示したり、情報を...あなたまたはサードに転送したりする義務を負いませんパーティ。読んだり送信したりしていない情報。プラットフォームとの契約関係が終了した後も、プラットフォームは引き続き以下の権利を享受することに同意するものとします。プラットフォームサービスを使用している間、ユーザーとすべてのトランザクション情報を保存し続けます。このプラットフォームのサービスを使用する過程で、この契約および/または規則に違反する違法な活動または行動に従事した場合、このプラットフォームは、この契約に従ってあなたに対して権利を主張することができます。プラットフォームがプラットフォームによって提供されるサービスを一時停止または終了した後、サービスの一時停止または終了前のトランザクションは次の原則に従って処理され、紛争、損失、または新たな損害は処理され、全責任を負います。 。次の処理で発生します。このプラットフォームで料金が請求されないこと、および損失や料金がないことを確認する必要があります：サービスを一時停止または終了する前にこのプラットフォームにアップロードされたビットコインおよびその他の暗号通貨は、一時停止またはそれを終了します。サービスが停止または終了する前に、実際には実行されていない別のメンバーと売買契約を結んでいました。プラットフォームは、売買契約、ビットコイン取引などを削除する権利を留保します。暗号通貨およびその他の暗号通貨に関する情報。他のメンバーと売買契約を結び、サービスが一時停止または終了する前に部分的に実行した場合、プラットフォームはトランザクションを削除できませんが、プラットフォームは同時にサービスを一時停止または終了する権利を有します。増加。相手に状況を通知します。

7.プライバシーポリシー
プラットフォームは、プラットフォームのプライバシーポリシーを随時公開および改訂し、プライバシーポリシーはこの契約の有効な部分を構成します。
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'KO'">
       이 개인 정보 보호 정책은 이 플랫폼의 모든 관련 서비스에 적용되며 이 플랫폼은 이 플랫폼의 서비스를 사용하는 모든 사용자의 개인 정보를 존중하고 보호합니다. 귀하에게 보다 정확하고 개인화된 서비스를 제공하기 위해 귀하의 개인 정보는 본 개인 정보 보호 정책의 규정에 따라 사용 및 공개되지만 이 플랫폼은 높은 수준의 근면과 신중을 기하여 이 정보를 취급합니다. 이 개인 정보 보호 정책에 달리 제공된 경우를 제외하고 이 플랫폼은 귀하의 사전 허가 없이 이 정보를 제3자에게 공개하거나 제공하지 않습니다. 이 플랫폼은 이 개인 정보 보호 정책을 수시로 업데이트합니다. 이 플랫폼의 서비스 계약에 동의하면 이 개인 정보 보호 정책의 전체 내용에 동의한 것으로 간주됩니다. 이 개인 정보 보호 정책은 서비스 계약의 필수적인 부분입니다.

1. 사용 범위
귀하가 당사 플랫폼에 로그인할 수 있는 계정을 등록하거나 활성화할 때 당사 계열사가 제공하는 다른 플랫폼에서 제공한 개인 등록 정보(회사의 요구에 따라 게시해야 하는 상호 및 기타 관련 산업 및 상업 등록 정보 제외) 법률 및 규정 및 자연인 운영자의 정보)), 귀하가 이 플랫폼 또는 이 플랫폼의 웹 페이지를 사용할 때 이 플랫폼은 또한 귀하의 브라우저 및 컴퓨터에 있는 정보(귀하의 IP 주소, 브라우저 유형을 포함하되 이에 국한되지 않음)를 기록합니다. , 사용 언어, ​​방문 날짜 및 데이터(예: 시간, 소프트웨어 및 하드웨어 기능 정보, 필요한 웹 페이지 기록), 이 플랫폼에서 비즈니스 파트너로부터 얻은 사용자 개인 데이터.
2. 정보이용
당사는 귀하의 사전 허가를 받지 않거나 제3자와 당사(당사의 계열사 포함)가 귀하에게 개별적으로 또는 공동으로 서비스를 제공하지 않는 한 관련 없는 제3자에게 귀하의 개인 정보를 제공, 판매, 임대, 공유 또는 거래하지 않습니다. 종료되면 이전에 액세스할 수 있었던 자료를 포함하여 그러한 모든 자료에 대한 액세스가 금지됩니다. 또한 제3자가 귀하의 개인 정보를 어떠한 수단으로도 무료로 수집, 편집, 판매 또는 배포하는 것을 허용하지 않습니다. 당사 플랫폼의 사용자가 위의 활동에 참여하는 경우 당사는 발견 즉시 사용자와의 서비스 계약을 종료할 권리가 있습니다.
3. 정보 공개
다음과 같은 경우에는 귀하의 개인 희망 또는 법률 규정에 따라 귀하의 개인 정보의 전부 또는 일부를 공개합니다: 귀하의 사전 동의를 얻은 제3자에게 공개, 귀하가 적격한 지적 재산권 침해 신고자이고 불만을 제기한 경우 , 피청구인의 요청에 따라 피청구인에게 공개하여 양측이 가능한 권리 분쟁을 처리할 수 있도록 하고, 법률의 관련 규정 또는 행정 또는 사법 기관의 요구 사항에 따라 제3자에게 제조업체 또는 행정 또는 사법 기관 법률, 규정 또는 당사의 서비스 계약 또는 관련 규칙을 제3자에게 공개해야 함 귀하가 필요로 하는 제품 및 서비스를 제공하기 위해 귀하는 귀하의 개인 정보를 제3자와 공유해야 함 거래 생성 시 플랫폼에서 거래 당사자가 거래 의무 및 정보 공개 요청을 이행하거나 부분적으로 이행하는 경우 당사는 거래 완료를 용이하게 하기 위해 상대방의 연락처 정보와 같은 필요한 정보를 사용자에게 제공하기로 결정할 권리가 있습니다. 거래 또는 분쟁 해결. 법률, 규정 또는 사이트 정책에 따라 적절하다고 판단되는 공개.
4. 정보의 저장 및 교환
당사가 귀하에 대해 수집하는 정보 및 데이터는 당사 및/또는 그 계열사의 서버에 저장되며, 이러한 정보 및 데이터는 귀하의 국가, 지역 또는 당사가 정보 및 데이터를 수집하는 장소 외부로 전송 및 액세스할 수 있습니다. 저장 및 표시.
5. 쿠키의 사용
쿠키 허용을 거부하지 않으면 쿠키를 사용하는 플랫폼 서비스 또는 기능에 로그인하거나 사용할 수 있도록 컴퓨터에 쿠키를 설정하거나 액세스합니다. 우리는 쿠키를 사용하여 판촉 서비스를 포함하여 보다 사려 깊고 개인화된 서비스를 제공합니다. 귀하는 쿠키를 수락하거나 거부할 권리가 있습니다. 브라우저에서 설정한 채널을 수정하여 쿠키 허용을 거부할 수 있습니다. 그러나 쿠키 허용을 거부하는 경우 로그인하거나 쿠키에 의존하는 플랫폼 서비스 또는 기능을 사용하지 못할 수 있습니다.
6. 정보 보안
귀하의 계정에는 보안 기능이 있으므로 계정 및 비밀번호 정보를 올바르게 보관하십시오. 다른 서버에 백업하고 사용자 비밀번호를 암호화하는 등의 보안 조치를 통해 귀하의 정보가 손실, 남용 및 변경되지 않도록 합니다. 전술한 보안 조치에도 불구하고 정보 네트워크에 대한 "완벽한 보안 조치"는 없음을 유의하시기 바랍니다. 온라인 거래를 위해 당사 플랫폼 서비스를 사용할 때 귀하는 불가피하게 연락처 정보 또는 우편 주소와 같은 귀하의 개인 정보를 거래상대방 또는 잠재적 거래상대방에게 공개하게 됩니다. 귀하의 개인정보를 적절하게 보호하고 필요한 경우에만 타인에게 제공하십시오. 귀하의 개인정보, 특히 계정 및 비밀번호가 유출된 것을 발견한 경우에는 즉시 당사 고객센터로 연락하여 조치를 취하도록 하십시오.
미성년자를 위한 특별 주의사항 귀하가 완전한 민권 및 민사 행위 능력을 갖춘 자연인이 아닌 경우 당사의 플랫폼 서비스를 사용할 권리가 없으므로 귀하가 당사에 개인 정보를 제공하지 않기를 바랍니다.

       귀하의 계정 서비스가 종료되거나 플랫폼에서 귀하의 계정 권한이 영구적으로 정지(취소)된 후, 플랫폼은 귀하를 위해 귀하의 계정에 있는 정보를 보유하거나 공개할 의무가 없으며 정보를 다음으로 전달할 의무도 없습니다. 귀하 또는 제3자 귀하가 읽거나 보내지 않은 정보. 귀하는 플랫폼과의 계약 관계가 종료된 후에도 플랫폼이 여전히 다음과 같은 권리를 향유한다는 데 동의합니다. 플랫폼 서비스를 사용하는 동안 사용자 정보와 모든 거래 정보를 계속 저장합니다. 이 플랫폼의 서비스를 사용하는 동안 이 계약 및/또는 규칙을 위반하는 불법 행위 또는 행동이 있는 경우 이 플랫폼은 여전히 ​​이 계약에 따라 귀하에게 권리를 주장할 수 있습니다. 플랫폼이 플랫폼이 귀하에게 제공하는 서비스를 중단 또는 종료한 후 서비스 중단 또는 종료 전의 귀하의 거래 행위는 다음 원칙에 따라 처리되며 귀하는 모든 분쟁, 손실 또는 새로운 손해를 처리하고 전적으로 부담해야 합니다. 다음 처리로 인해 발생하는 모든 수수료 및 이 플랫폼이 손실이나 비용이 없는지 확인해야 합니다. 서비스 중단 또는 종료 전에 이 플랫폼에 업로드한 비트코인 ​​및 기타 가상 통화와 같은 가상 통화가 아직 발생하지 않은 경우 이 플랫폼은 서비스를 중단 또는 종료할 때 이 항목의 관련 정보를 삭제할 권리가 있습니다 서비스가 중단 또는 종료되기 전에 다른 회원과 판매 계약을 체결했지만 계약이 실제로 수행되지 않은 경우 플랫폼은 판매 계약 및 비트코인 ​​등의 거래를 삭제할 권리가 있습니다. 가상 화폐 및 기타 가상 화폐에 대한 정보, 서비스가 중단 또는 종료되기 전에 다른 회원과 판매 계약을 체결하고 일부 수행한 경우, 플랫폼은 거래를 삭제할 수 없지만 플랫폼은 서비스를 일시 중단하거나 종료하는 것과 동시에 상대방에게 상황을 알릴 권리가 있습니다.

7. 개인정보 보호정책
이 플랫폼은 때때로 이 플랫폼에 대한 개인 정보 보호 정책을 게시하고 수정할 것이며 개인 정보 보호 정책은 이 계약의 효과적인 부분을 구성합니다.
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'DE'">
       Diese Datenschutzrichtlinie gilt für alle zugehörigen Dienste dieser Plattform, und diese Plattform respektiert und schützt die Privatsphäre aller Benutzer, die die Dienste dieser Plattform nutzen. Um Ihnen genauere und personalisiertere Dienstleistungen anbieten zu können, werden Ihre personenbezogenen Daten gemäß den Bestimmungen dieser Datenschutzrichtlinie verwendet und offengelegt, aber diese Plattform wird diese Daten mit einem hohen Maß an Sorgfalt behandeln. Sofern in dieser Datenschutzrichtlinie nicht anders angegeben, wird diese Plattform diese Informationen ohne Ihre vorherige Zustimmung nicht an Dritte weitergeben oder weitergeben. Diese Plattform wird diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wenn Sie der Servicevereinbarung dieser Plattform zustimmen, wird davon ausgegangen, dass Sie dem gesamten Inhalt dieser Datenschutzrichtlinie zustimmen. Diese Datenschutzrichtlinie ist ein integraler Bestandteil der Servicevereinbarung.

1. Umfang der Nutzung
Wenn Sie ein Konto registrieren oder aktivieren, mit dem Sie sich auf unserer Plattform anmelden können, werden die persönlichen Registrierungsinformationen, die Sie auf anderen Plattformen bereitstellen, von unseren verbundenen Unternehmen bereitgestellt (mit Ausnahme des Firmennamens und anderer relevanter Unternehmensregistrierungsinformationen, die gemäß bereitgestellt werden müssen mit den Anforderungen von Gesetzen und Vorschriften und persönlichen Registrierungsinformationen) Betreiberinformationen)); Wenn Sie diese Plattform oder ihre Website nutzen, zeichnet diese Plattform auch Ihre Browser- und Computerinformationen auf, einschließlich, aber nicht beschränkt auf Ihre IP-Adresse, Browsertyp, Sprache verwendet, Daten wie Datum und Uhrzeit des Zugriffs, Softwareinformationen und Hardwarefunktionen, die Sie benötigen, und Website-Aufzeichnungen; personenbezogene Benutzerdaten, die diese Plattform von Geschäftspartnern erhält.
2. Verwendung von Informationen
Wir werden Ihre personenbezogenen Daten nicht an unabhängige Dritte verkaufen, vermieten, weitergeben oder damit handeln, es sei denn, wir erhalten Ihre vorherige Zustimmung oder der Dritte und wir (einschließlich unserer verbundenen Unternehmen) erbringen einzeln oder gemeinsam Dienstleistungen für Sie, und wenn nach Beendigung der Dienstleistung Der Zugriff auf alle diese Materialien, einschließlich zuvor zugänglicher Materialien, ist verboten. Wir gestatten auch keinem Dritten, Ihre personenbezogenen Daten in irgendeiner Weise kostenlos zu erheben, zu verarbeiten, zu verkaufen oder zu verteilen. Wenn ein Benutzer unserer Plattform die oben genannten Aktivitäten ausführt, sind wir berechtigt, den Dienstleistungsvertrag mit dem Benutzer sofort nach Entdeckung zu kündigen.
3. Offenlegung von Informationen
Wir werden Ihre personenbezogenen Daten ganz oder teilweise gemäß Ihren persönlichen Wünschen oder gesetzlichen Anforderungen in folgenden Fällen übermitteln: an einen Dritten mit Ihrer vorherigen Zustimmung; wenn Sie ein qualifizierter Beschwerdeführer für geistiges Eigentum sind und eine Beschwerde eingereicht haben, an die Antrag des Beklagten, dem Beklagten die Möglichkeit zu geben, potenzielle Rechtsstreitigkeiten beizulegen; Dritthersteller oder Verwaltungs- oder Justizbehörden gemäß den einschlägigen Rechtsvorschriften oder Anforderungen der Verwaltungs- oder Justizbehörden; Gesetze, Vorschriften oder unser Servicevertrag oder relevante Vorschriften müssen offengelegt werden an Dritte; um die von Ihnen angeforderten Produkte und Dienstleistungen bereitzustellen, müssen Sie Ihre personenbezogenen Daten an Dritte weitergeben; bei Transaktionen, die auf unserer Plattform erstellt werden, wenn eine Partei der Transaktion Transaktionspflichten und Informationsoffenlegungspflichten erfüllt oder teilweise erfüllt, wir haben das Recht zu entscheiden, Benutzern notwendige Informationen wie die Kontaktinformationen der Gegenpartei zur Verfügung zu stellen, um den Abschluss der Transaktion zu erleichtern und die Beilegung der Transaktion oder Streitigkeit zu erleichtern. Offenlegungen, die wir in Übereinstimmung mit Gesetzen, Vorschriften oder Richtlinien der Website für angemessen halten.
4. Speicherung und Weitergabe von Informationen
Die Informationen und Daten, die wir über Sie sammeln, werden auf unseren Servern und/oder den Servern unserer verbundenen Unternehmen gespeichert, die sich möglicherweise außerhalb Ihres Landes, Ihrer Region oder Ihres Standorts befinden, an dem wir sie sammeln, übertragen und abrufen. Speicherung und Anzeige.
5. Verwendung von Cookies
Sofern Sie die Annahme von Cookies nicht ablehnen, werden wir Cookies auf Ihrem Computer platzieren oder darauf zugreifen, damit Sie sich anmelden oder unsere Plattformdienste oder -funktionen nutzen können
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'ES'">
       Esta declaración de privacidad se aplica a todos los servicios relacionados de esta plataforma, y ​​esta plataforma respeta y protege la privacidad personal de todos los usuarios que utilizan los servicios de esta plataforma. Con el fin de brindarle servicios más precisos y personalizados, su información personal será utilizada y divulgada de conformidad con lo establecido en esta Política de Privacidad, pero esta plataforma tratará dicha información con un alto grado de diligencia y prudencia. Excepto que se indique lo contrario en esta Política de privacidad, esta plataforma no divulgará ni proporcionará esta información a terceros sin su permiso previo. Esta plataforma actualizará esta política de privacidad de vez en cuando. Cuando acepta el acuerdo de servicio de esta plataforma, se considera que ha aceptado todo el contenido de esta política de privacidad. Esta Política de Privacidad es una parte integral del Acuerdo de Servicio.

1 Alcance
Cuando se registra o activa una cuenta que puede iniciar sesión en nuestra plataforma, su información de registro personal proporcionada por nuestros afiliados en otras plataformas (excepto el nombre de la empresa y otra información de registro industrial y comercial relevante que debe divulgarse de acuerdo con la ley); regulaciones , información de operadores de personas físicas); cuando utiliza esta plataforma o sus páginas web, esta plataforma también registrará información en su navegador y computadora, que incluye, entre otros, su dirección IP, tipo de navegador, idioma utilizado, fecha de visita, Hora y otros datos, información sobre las funciones de software y hardware que necesita y registros web; datos personales de usuario obtenidos por esta plataforma de socios comerciales.
2. Uso de la Información
No proporcionaremos, venderemos, alquilaremos, compartiremos ni intercambiaremos su información personal con ningún tercero no relacionado a menos que obtengamos su permiso previo, o que el tercero y nosotros (incluidas nuestras afiliadas) le brindemos servicios de forma individual o conjunta, y proporcionemos servicios posteriores. servicio de ventas Para este propósito, tiene prohibido acceder a todos esos materiales, incluidos los materiales a los que haya accedido anteriormente. Tampoco permitimos que ningún tercero recopile, edite, venda o difunda su información personal de forma gratuita. Si algún usuario de nuestra plataforma participa en las actividades anteriores, tenemos el derecho de rescindir el acuerdo de servicio con el usuario inmediatamente después del descubrimiento.
3. Divulgación de información
Divulgaremos su información personal en su totalidad o en parte de acuerdo con sus deseos personales o requisitos legales en los siguientes casos: Divulgación a terceros con su consentimiento previo; si usted es un denunciante calificado de propiedad intelectual y ha presentado una queja, debe ser objeto de un reclamo A solicitud de la persona, se le dará a conocer al demandado para que las dos partes puedan discutir posibles disputas de derechos; de acuerdo con las disposiciones pertinentes de la ley, o los requisitos de las instituciones administrativas o judiciales, se se proporciona a terceros fabricantes o instituciones administrativas o judiciales; las leyes, reglamentos o nuestros acuerdos de servicio o reglas relacionadas deben divulgarse a terceros; para proporcionar los productos y servicios que necesita, debe compartir su información personal con terceros ; en las transacciones creadas en nuestra plataforma, si alguna de las partes de la transacción cumple o cumple parcialmente con las obligaciones de la transacción y los requisitos de divulgación de información, tenemos el derecho de optar por proporcionar a los usuarios la información necesaria, como la información de contacto de la contraparte, para facilitar la finalización de la transacción o la resolución de disputas. Divulgaciones que consideremos apropiadas de acuerdo con cualquier ley, reglamento o política del sitio.
4. Almacenamiento e intercambio de información
La información y los datos que recopilamos sobre usted se almacenarán en nuestros servidores y/o en los de nuestras afiliadas, y dicha información y datos pueden transferirse y transferirse a un lugar que no sea su país, región o ubicación donde recopilamos la información y acceso a datos almacenamiento y visualización.
5. Uso de cookies
Si no se niega a aceptar cookies, estableceremos o accederemos a cookies en su computadora para que pueda iniciar sesión o utilizar servicios o funciones de nuestra plataforma que dependen de cookies. Usamos cookies para brindarle un servicio más atento y personalizado, incluidas ofertas promocionales. Tiene derecho a optar por aceptar o rechazar las cookies. Puede negarse a aceptar las cookies modificando el canal establecido por su navegador. Sin embargo, si elige rechazar las cookies, es posible que no pueda iniciar sesión o utilizar los servicios o funciones.
        </pre>
        <pre class="font-Four" v-show="$i18n.locale == 'FR'">
       Cette déclaration de confidentialité s'applique à tous les services connexes de cette plate-forme, et cette plate-forme respecte et protège la vie privée de tous les utilisateurs qui utilisent les services de cette plate-forme. Afin de vous fournir des services plus précis et personnalisés, vos informations personnelles seront utilisées et divulguées conformément aux dispositions de la présente politique de confidentialité, mais cette plateforme traitera ces informations avec un degré élevé de soin. Sauf disposition contraire dans la présente politique de confidentialité, la plate-forme ne divulguera ni ne fournira ces informations à des tiers sans votre autorisation préalable. Cette plate-forme mettra à jour cette politique de confidentialité de temps à autre. Lorsque vous acceptez le contrat de service de cette plateforme, vous êtes réputé avoir accepté l'intégralité du contenu de cette politique de confidentialité. Cette politique de confidentialité fait partie intégrante du contrat de service.

1. Zone d'utilisation
Lorsque vous vous enregistrez ou activez un compte permettant de vous connecter à notre plateforme, les informations d'enregistrement personnelles fournies par nos affiliés sur d'autres plateformes (à l'exclusion des noms commerciaux et autres informations d'enregistrement industriel et commercial pertinentes, qui doivent être publiées conformément aux exigences de l'entreprise) lois et réglementations, informations sur l'opérateur (personne physique) ); lorsque vous utilisez cette plate-forme ou ses pages Web, cette plate-forme enregistrera également les informations de votre navigateur et de votre ordinateur, y compris, mais sans s'y limiter, votre adresse IP, le type de navigateur, la langue utilisée, la date d'accès et le temps, les logiciels et le matériel et les autres données dont vous avez besoin, les informations fonctionnelles et les enregistrements de pages Web ; les données personnelles des utilisateurs obtenues par cette plate-forme auprès de partenaires commerciaux.
2. Utilisation des informations
Nous ne fournirons, ne vendrons, ne louerons, ne partagerons ni n'échangerons vos informations personnelles avec des tiers non liés, sauf si nous obtenons votre autorisation préalable, ou si le tiers et nous (y compris nos sociétés affiliées) vous fournissons individuellement ou conjointement des services, Et après la fin du service , il lui sera interdit d'accéder à tous ces éléments, y compris ceux auxquels il a pu accéder auparavant. Nous n'autorisons pas non plus un tiers à collecter, modifier, vendre ou distribuer vos informations personnelles gratuitement de quelque manière que ce soit. Si un utilisateur de notre plateforme s'engage dans les activités ci-dessus, nous avons le droit de résilier le contrat de service avec l'utilisateur immédiatement après la découverte.
3. Divulgation d'informations
Nous divulguerons vos informations personnelles en tout ou en partie selon vos souhaits personnels ou les exigences légales dans les cas suivants : à un tiers avec votre consentement préalable ; si vous êtes un demandeur qualifié des droits de propriété intellectuelle et avez intenté une action en justice, à la demande du défendeur, communiquée au défendeur afin que les deux parties puissent résoudre d'éventuels conflits de droits ; conformément aux dispositions pertinentes de la loi, ou aux exigences des institutions administratives ou judiciaires, à des fabricants tiers ou à des institutions administratives ou judiciaires ; les lois, réglementations ou notre accord de service ou les règles connexes doivent être divulgués à des tiers ; afin de fournir les produits et services dont vous avez besoin, vous devez partager vos informations personnelles avec des tiers ; dans les transactions créées sur notre plate-forme, si une partie à la transaction remplit ou remplit partiellement ses obligations de transaction et demande la divulgation d'informations, nous avons le droit de décider de fournir à l'utilisateur les informations nécessaires telles que les coordonnées de la contrepartie pour faciliter la réalisation de la transaction ou la résolution des litiges. Divulgations que nous jugeons appropriées conformément à toute loi, réglementation ou politique du site.
4. Stockage et échange d'informations
Les informations et les données que nous collectons à votre sujet seront stockées sur nos serveurs et/ou ceux de nos sociétés affiliées, qui peuvent être transmises et accessibles en dehors de votre pays, région ou emplacement où nous collectons les informations et les données, stockées et affichées.
5. Utilisation des cookies
Si vous ne refusez pas d'accepter les cookies, nous installerons ou accéderons à des cookies sur votre ordinateur afin que vous puissiez vous connecter ou utiliser les services ou fonctionnalités de notre plateforme qui reposent sur les cookies.
        </pre>
        <pre class="font-Four" v-show="$i18n.locale == 'IT'">
       Questa politica sulla privacy si applica a tutti i servizi correlati di questa piattaforma e questa piattaforma rispetta e protegge la privacy personale di tutti gli utenti che utilizzano i servizi di questa piattaforma. Al fine di fornirti servizi più accurati e personalizzati, i tuoi dati personali saranno utilizzati e diffusi in conformità a quanto previsto dalla presente Privacy Policy, ma questa piattaforma tratterà tali informazioni con un elevato grado di diligenza e prudenza. Salvo quanto diversamente previsto nella presente Informativa sulla privacy, questa piattaforma non divulgherà o fornirà queste informazioni a terzi senza il tuo previo consenso. Questa piattaforma aggiornerà questa politica sulla privacy di volta in volta. Quando accetti il ​​contratto di servizio di questa piattaforma, si presume che tu abbia accettato l'intero contenuto della presente informativa sulla privacy. La presente Informativa sulla privacy è parte integrante del Contratto di servizio.

1. Ambito di utilizzo
Quando registri o attivi un account che può accedere alla nostra piattaforma, le tue informazioni personali di registrazione (tranne il nome della società e altre informazioni relative alla registrazione dell'attività, che devono essere pubblicate come richiesto dalla società) fornite dai nostri affiliati su altre piattaforme, leggi e regolamenti , e le persone fisiche Dati dell'Operatore)); quando utilizzi questa piattaforma o le sue pagine web, questa piattaforma registrerà anche informazioni sul tuo browser e computer, inclusi, a titolo esemplificativo ma non esaustivo, indirizzo IP, tipo di browser, lingua utilizzata, dati come data e ora di accesso, funzioni software e hardware richieste e record di pagine Web; dati personali degli utenti ottenuti da questa piattaforma da partner commerciali.
2. Uso delle informazioni
Non forniremo, venderemo, affitteremo, condivideremo o scambieremo le tue informazioni personali con terze parti non correlate a meno che non otteniamo il tuo permesso in anticipo, o la terza parte e noi (inclusi i nostri affiliati) individualmente o congiuntamente dopo il termine del servizio La fornitura dei Servizi da parte dell'utente disabiliterà l'accesso a tutti questi materiali, compresi i materiali precedentemente accessibili. Inoltre, non consentiamo a terzi di raccogliere, modificare, vendere o divulgare le tue informazioni personali in alcun modo gratuitamente. Se un utente della nostra piattaforma si impegna nelle attività di cui sopra, abbiamo il diritto di risolvere il contratto di servizio con l'utente immediatamente dopo la scoperta.
3. Divulgazione delle informazioni
Divulgheremo le tue informazioni personali in tutto o in parte in conformità con i tuoi desideri personali o requisiti legali nelle seguenti circostanze: Divulgazione a terzi con il tuo consenso; se sei un denunciante qualificato di proprietà intellettuale e hai presentato un reclamo, dovresti Su richiesta del resistente, è comunicato al resistente affinché le parti possano risolvere eventuali controversie in materia di diritti; secondo le disposizioni di legge in materia, o come richiesto da un organo amministrativo o giudiziario, a produttori terzi o organi amministrativi o giudiziari; le leggi, i Regolamenti o il nostro contratto di servizio o le norme correlate devono essere comunicati a terzi; per fornire i prodotti e servizi richiesti è necessario condividere le tue informazioni personali con terzi; nelle transazioni realizzate sul nostro piattaforma, se una parte della transazione esegue o parte dell'adempimento degli obblighi di transazione e dei requisiti di divulgazione delle informazioni, abbiamo il diritto di decidere di fornirti le informazioni necessarie come le informazioni di contatto della controparte per facilitare il completamento della transazione o il risoluzione delle controversie. Divulgazioni che riteniamo appropriate in conformità con qualsiasi legge, regolamento o politica del sito.
4. Archiviazione e scambio di informazioni
Le informazioni e i dati che raccogliamo su di te verranno archiviati sui server nostri e/o delle nostre società affiliate e potrebbero essere trasmessi e accessibili al di fuori del tuo paese, regione o luogo in cui raccogliamo le informazioni. e visualizzare.
5. Utilizzo dei cookie
Se non rifiuti di accettare i cookie, imposteremo o accederemo ai cookie sul tuo computer in modo che tu possa accedere o utilizzare i servizi o le funzionalità della nostra piattaforma che si basano sui cookie. Utilizziamo i cookie per fornirti un servizio più ponderato e personalizzato, comprese le offerte promozionali. Hai il diritto di scegliere se accettare o rifiutare i cookie. Puoi rifiutarti di accettare i cookie modificando i canali nelle impostazioni del tuo browser. Tuttavia, se scegli di rifiutare i cookie, puoi
        </pre>

        <pre class="font-Four" v-show="$i18n.locale == 'PT'">
Esta declaração de privacidade aplica-se a todos os serviços relevantes da plataforma, respeitando e protegendo a privacidade pessoal de todos os usuários que usam os serviços da plataforma. A fim de lhe fornecer serviços mais precisos e personalizados, usaremos e divulgaremos suas informações pessoais de acordo com as disposições desta política de privacidade, mas a plataforma tratará essas informações com alta diligência e prudência. Salvo especificação em contrário nesta política de privacidade, a plataforma não divulgará essas informações ao público ou as fornecerá a fabricantes terceiros sem sua permissão prévia. Esta plataforma atualizará esta política de privacidade de tempos em tempos. Quando você concorda com o contrato de serviço da plataforma, considera-se que você concordou com todo o conteúdo desta política de privacidade. Esta política de privacidade é parte integrante do contrato de serviço.
1. Âmbito de utilização
Quando você registra ou inicia uma conta que pode fazer login em nossa plataforma, as informações pessoais de registro fornecidas por você em outras plataformas fornecidas por nossas empresas afiliadas (excluindo as informações relevantes de registro industrial e comercial, como o nome da empresa, que deve ser divulgado de acordo com leis e regulamentos e as informações de operadores de pessoas físicas); Quando você usa a plataforma ou suas páginas da web, as informações registradas pela plataforma em seu navegador e computador, incluindo, mas não limitado a, seu endereço IP, tipo de navegador, idioma usado, data e hora de acesso, informações de recursos de software e hardware e registros de páginas da web exigidos por você; Esta plataforma acessa dados pessoais do usuário obtidos de parceiros de negócios.
2. Utilização da informação
Nós não forneceremos, venderemos, alugaremos, compartilharemos ou trocaremos suas informações pessoais a qualquer fabricante terceiro não relacionado, a menos que você tenha obtido sua permissão com antecedência, ou o fabricante terceiro e nós (incluindo nossas afiliadas) fornecemos serviços para você individualmente ou em conjunto, e após o término do serviço, eles serão proibidos de acessar todos esses dados, incluindo aqueles que podem acessar antes. Também não permitimos que fabricantes terceiros coletem, editem, vendam ou divulguem suas informações pessoais gratuitamente por qualquer meio. Se qualquer usuário de nossa plataforma se envolver nas atividades acima, temos o direito de rescindir imediatamente o contrato de serviço com esse usuário uma vez encontrado.
3. Divulgação de informações
Nas seguintes circunstâncias, divulgaremos suas informações pessoais no todo ou em parte de acordo com sua vontade pessoal ou as disposições da lei: com seu consentimento prévio, divulgaremos essas informações a terceiros; Se você é um reclamante qualificado de propriedade intelectual e apresentou uma reclamação, você deve divulgá-la ao respondente a pedido do respondente, para que ambas as partes possam lidar com possíveis disputas de direitos; De acordo com as disposições relevantes da lei ou as exigências das autoridades administrativas ou judiciais, divulgar ao fabricante terceiro ou às autoridades administrativas ou judiciais; Se você violar as leis, regulamentos relevantes ou nosso contrato de serviço ou regras relevantes, você precisa divulgar a terceiros; Para fornecer os produtos e serviços que você precisa, você deve compartilhar suas informações pessoais com fabricantes terceirizados; Em uma transação criada em nossa plataforma, se qualquer parte da transação cumpriu ou cumpriu parcialmente as obrigações da transação e fez um pedido de divulgação de informações, temos o direito de decidir fornecer ao usuário as informações necessárias, como as informações de contato de sua contraparte para facilitar a conclusão da transação ou a resolução de disputas. Consideramos a divulgação apropriada de acordo com leis, regulamentos ou políticas do site.
4. Armazenamento e intercâmbio de informações
As informações e dados coletados por nós sobre você serão armazenados nos servidores de nós e/ou de suas afiliadas. Essas informações e dados podem ser transmitidos para seu país, região ou fora do país onde coletamos informações e dados, e serão acessados, armazenados e exibidos fora do país.
5. Utilização de cookies
Se você não se recusar a aceitar cookies, definiremos ou acessaremos cookies em seu computador para que você possa fazer login ou usar nossos serviços de plataforma ou funções que dependem de cookies. Usamos cookies para lhe fornecer serviços personalizados mais atenciosos, incluindo serviços promocionais. Você tem o direito de aceitar ou rejeitar cookies. Você pode se recusar a aceitar cookies modificando as configurações do navegador. No entanto, se optar por recusar a aceitação de cookies, poderá não conseguir iniciar sessão ou utilizar os nossos serviços de plataforma ou funções que dependem de cookies.
6. Segurança da informação
Sua conta tem função de proteção de segurança. Por favor, mantenha suas informações de conta e senha corretamente. Garantiremos que suas informações não sejam perdidas, abusadas ou alteradas por meio de backup em outros servidores, criptografia de senhas de usuário e outras medidas de segurança. Apesar das medidas de segurança acima, observe também que não há "medidas de segurança perfeitas" na rede de informações. Ao usar nossos serviços de plataforma para realizar transações on-line, você inevitavelmente divulgará suas informações pessoais, como informações de contato ou endereço postal, à contraparte ou potencial contraparte. Proteja adequadamente as suas informações pessoais e apenas as forneça a outras pessoas quando necessário. Se você descobrir que suas informações pessoais vazaram, especialmente sua conta e senha, entre em contato com nosso serviço de atendimento ao cliente imediatamente para que possamos tomar as medidas correspondentes.
Precauções especiais para menores Se você não é uma pessoa física com plena capacidade para direitos civis e plena capacidade para conduta civil, você não tem o direito de usar nossos serviços de plataforma. Portanto, esperamos que você não nos forneça nenhuma informação pessoal.
Depois que o serviço da sua conta é encerrado ou a licença da sua conta na plataforma é permanentemente congelada (cancelada), a plataforma não tem obrigação de reter ou divulgar qualquer informação na sua conta para você, nem de encaminhar qualquer informação que você não leu ou enviou a você ou a terceiros. Você concorda que, após o término de sua relação contratual com a plataforma, a plataforma ainda tem os seguintes direitos: continuar salvando suas informações de usuário e todas as informações de transação durante o uso dos serviços da plataforma. Se você violar a lei ou o contrato e/ou regras durante o uso dos serviços da plataforma, a plataforma ainda pode reivindicar direitos contra você de acordo com o contrato. Após a plataforma suspender ou encerrar os serviços prestados a você pela plataforma, sua transação antes da suspensão ou rescisão do serviço será tratada de acordo com os seguintes princípios, e você deve lidar independentemente e suportar plenamente quaisquer disputas, perdas ou novos custos decorrentes do seguinte processamento: Também devemos garantir que a plataforma esteja livre de qualquer perda ou despesa decorrente disso. Se a moeda virtual, como Bitcoin, que você carregou para a plataforma antes da suspensão ou rescisão do serviço não tiver sido negociada, a plataforma tem o direito de excluir as informações relevantes deste item ao mesmo tempo que a suspensão ou rescisão do serviço; Se você celebrou um contrato de venda com outros membros antes da suspensão ou rescisão do serviço, mas o contrato não foi efetivamente executado, a plataforma tem o direito de excluir o contrato de venda e as informações relacionadas à transação de moedas virtuais como Bitcoin; Se você chegou a um acordo de compra e venda com outros membros antes da suspensão ou rescisão do serviço e o executou parcialmente, a plataforma não pode excluir a transação, mas a plataforma tem o direito de notificar sua contraparte da situação relevante enquanto suspende ou encerra o serviço.
7. Política de Privacidade
A plataforma publicará e revisará a política de privacidade periodicamente no site da plataforma, e a política de privacidade constitui uma parte efetiva deste acordo.
        </pre>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
.privacy {
  min-height: calc(100vh - 230px);
  padding-bottom: 100px;
}
.agree_box {
  margin-top: 20px;
  padding: 15px;
  min-height: calc(100vh - 60px);
  // white-space: pre-line;
  pre {
    white-space: pre-wrap;
    white-space: -moz-pre-wrap;
    white-space: -pre-wrap;
    white-space: -o-pre-wrap;
    word-wrap: break-word;
    line-height: 30px;
  }
}
</style>
